language: node_js
node_js:
  - "node"
  
before_install: 
  - cd angular-oauth2-oidc
  
before_script:
  - npm install -g gulp-cli

  
script: gulp build

before_deploy:
  - cd src/dist

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  
  on:
    tags: true

